version: '3.4'

services:
  server:
    build:
      context: ./
      dockerfile: ./docker_files/Dockerfile.build
      target: serv
    command: 'yarn nodemon ./src'
    networks:
        - musicnet
    ports: 
        - '4000:4000'
    volumes: 
      - ./src:/code

networks: 
  musicnet: